name: golden_bricks
description: A better font for golden tests

version: 1.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  golden_toolkit: ^0.13.0

flutter:
  fonts:
    - family: GoldenBricks
      fonts:
        - asset: packages/golden_bricks/golden_bricks.ttf
