name: golden_bricks_docs
description: Documentation for Golden Bricks
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  static_shock: any

dependency_overrides:
  static_shock:
    path: /Users/matt/Projects/static_shock/packages/static_shock

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
